import React from 'react';
import ProductCard from '../../components/cards/ProductCard';
import { PRODUCTS } from '../../data/products';

function CustomerRecommendations() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-heading font-bold text-neutral-900">AI Recommendations</h1>
        <p className="text-xs text-neutral-500 mt-1">Smart product & service suggestions generated by HunarHub ML service.</p>
      </div>

      {/* Required Placeholder Box */}
      <div className="p-8 bg-gradient-to-r from-purple-600 via-indigo-600 to-purple-800 text-white rounded-3xl shadow-lg">
        <div className="max-w-xl space-y-3">
          <span className="bg-white/20 text-white text-[10px] font-bold px-3 py-1 rounded-full uppercase tracking-wider">
            🤖 AI Service Integration Placeholder
          </span>
          <h2 className="text-2xl font-heading font-bold">Personalized recommendations will appear here.</h2>
          <p className="text-xs text-purple-100 leading-relaxed">
            In Phase 4, our Python FastAPI microservice using Scikit-learn collaborative filtering will analyze your browsing history and purchase patterns to suggest relevant local micro-entrepreneurs.
          </p>
        </div>
      </div>

      <div className="space-y-4">
        <h2 className="text-lg font-heading font-bold text-neutral-900">Sample Recommended Products for You</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {PRODUCTS.slice(0, 3).map((product) => (
            <ProductCard key={product.id} product={product} />
          ))}
        </div>
      </div>
    </div>
  );
}

export default CustomerRecommendations;
